import ships from "../../server/lib/ships.js";
import { FactionConfig } from "../baseFactions.js"

export const republic = new FactionConfig("Republic", "#CA5533", "REPUBLIC")
    .addBuildableShips(1, "CR90_REPUBLIC", "CONSOLAR_REPUBLIC", "PELTA_REPUBLIC", "CLASS_C_REPUBLIC", "ARQUITENS_REPUBLIC", "CARRACK_REPUBLIC", "SUPER_TRANSPORT_VI_REPUBLIC")
    .addBuildableShips(2, "ACCLIMATOR_REPUBLIC", "DREADNOUGHTHEAVYCRUISER_REPUBLIC", "SUPER_TRANSPORT_VII_REPUBLIC")
    .addBuildableShips(3, "VENATOR_REPUBLIC", "ACCLIMATOR_BATTLESHIP_REPUBLIC")
    .addBuildableShips(4, "PROCURATOR_REPUBLIC", "MAELSTROM_REPUBLIC", "PRAETOR_REPUBLIC", "SECUTOR_REPUBLIC", "MANDATOR_ONE_REPUBLIC", "MANDATOR_TWO_REPUBLIC")
    .addStationOptions("GOLAN_I_REPUBLIC", "GOLAN_II_REPUBLIC", "GOLAN_III_REPUBLIC")
    .addShipyardOptions("SHIPYARD_LVL_1_REPUBLIC", "SHIPYARD_LVL_2_REPUBLIC", "SHIPYARD_LVL_3_REPUBLIC", "SHIPYARD_LVL_4_REPUBLIC");


export const cis = new FactionConfig("CIS", "#5533C8", "CIS")
    .addBuildableShips(1, "DIAMOND_CIS", "HARDCELL_CIS", "LUPUSMISSILEFRIGATE_CIS", "C9979_CIS", "MUNIFICENT_CIS")
    .addBuildableShips(2, "RECUSANT_CIS", "SABOATHDESTROYER_CIS", "MUNIFICENT_HEAVY_CIS", "LUCREHULK_CORE_SHIP_CIS")
    .addBuildableShips(3, "PROVIDENCEDESTROYER_CIS", "DHOMNI_CIS", "LUCREHULKAUXILIARYWARSHIP_CIS", "LUCREHULKBATTLESHIP_CIS", "LUCREHULK_CONTROL_CIS")
    .addBuildableShips(4, "PROVIDENCEDREADNOUGHT_CIS", "RECUSANTDREADNOUGHT_CIS", "BULWARKII_CIS", "SUBJUGATOR_CIS", "DEVASTATION_CIS")
    .addStationOptions("GOLAN_I_CIS", "GOLAN_II_CIS", "GOLAN_III_CIS")
    .addShipyardOptions("SHIPYARD_LVL_1_CIS", "SHIPYARD_LVL_2_CIS", "SHIPYARD_LVL_3_CIS", "SHIPYARD_LVL_4_CIS");
