import { FactionConfig } from "../baseFactions.js"


export const empire = new FactionConfig("Galactic Empire", "#55EE55", "EMPIRE")
    .addBuildableShips(1, "RAIDER_EMPIRE", "VIGILCORVETTE_EMPIRE", "QUASAR_EMPIRE", "CARRACK_EMPIRE", "LANCERFRIGATE_EMPIRE", "TONFALKCARRIER_EMPIRE", "STRIKECRUISER_EMPIRE", "STARGALLEON_EMPIRE", "VICTORYFRIGATE_EMPIRE")
    .addBuildableShips(2, "ARQUITENS_EMPIRE", "IMOBILIZER_EMPIRE", "DREADNOUGHTHEAVYCRUISER_EMPIRE", "ACCLIMATOR_EMPIRE", "IMPERIAL_II_EMPIRE", "GLADIATOR_EMPIRE", "VINDICATOR_EMPIRE", "PURSUIT_EMPIRE", "VENATOR_EMPIRE")
    .addBuildableShips(3, "IMPERIAL_CARGO_SHIP_EMPIRE", "VICTORYSTARDESTROYER_EMPIRE", "CRIMSONCOMMAND_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "AGGRESSORSTARDESTROYER_EMPIRE", "ALLEGIANCE_EMPIRE", "TORPEDO_SPHERE_EMPIRE")
    .addBuildableShips(4, "CONSOLIDATORASSAULTSHIP_EMPIRE", "COMPELLOR_EMPIRE", "ARCHAMMER_EMPIRE", "EXECUTORSUPERSTARDESTROYER_EMPIRE", "BELLATORSUPERSTARDESTROYER_EMPIRE", "ASSERTORSTARDREADNOUGHT_EMPIRE", "LEGATORSTARDREADNOUGHT_EMPIRE", "VENGEANCE_EMPIRE");

export const maldrood = new FactionConfig("Greater Maldrood", "#D85555", "EMPIRE")
    .addBuildableShips(1, "RAIDER_EMPIRE", "VIGILCORVETTE_EMPIRE", "QUASAR_EMPIRE", "CARRACK_EMPIRE", "LANCERFRIGATE_EMPIRE", "TONFALKCARRIER_EMPIRE", "STRIKECRUISER_EMPIRE", "STARGALLEON_EMPIRE", "VICTORYFRIGATE_EMPIRE")
    .addBuildableShips(2, "ARQUITENS_EMPIRE", "IMOBILIZER_EMPIRE", "DREADNOUGHTHEAVYCRUISER_EMPIRE", "ACCLIMATOR_EMPIRE", "IMPERIAL_II_EMPIRE", "GLADIATOR_EMPIRE", "VINDICATOR_EMPIRE", "PURSUIT_EMPIRE", "VENATOR_EMPIRE")
    .addBuildableShips(3, "IMPERIAL_CARGO_SHIP_EMPIRE", "VICTORYSTARDESTROYER_EMPIRE", "CRIMSONCOMMAND_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "AGGRESSORSTARDESTROYER_EMPIRE", "ALLEGIANCE_EMPIRE", "TORPEDO_SPHERE_EMPIRE")
    .addBuildableShips(4, "CONSOLIDATORASSAULTSHIP_EMPIRE", "COMPELLOR_EMPIRE", "ARCHAMMER_EMPIRE", "EXECUTORSUPERSTARDESTROYER_EMPIRE", "BELLATORSUPERSTARDESTROYER_EMPIRE", "ASSERTORSTARDREADNOUGHT_EMPIRE", "LEGATORSTARDREADNOUGHT_EMPIRE", "VENGEANCE_EMPIRE");
