import ships from "../../server/lib/ships.js";
import { FactionConfig } from "../baseFactions.js"

export const empire = new FactionConfig("Galactic Empire", "#55EE55", "EMPIRE")
    .addBuildableShips(1, "RAIDER_EMPIRE", "VIGILCORVETTE_EMPIRE", "QUASAR_EMPIRE", "CARRACK_EMPIRE", "LANCERFRIGATE_EMPIRE", "TONFALKCARRIER_EMPIRE", "STRIKECRUISER_EMPIRE", "STARGALLEON_EMPIRE", "VICTORYFRIGATE_EMPIRE")
    .addBuildableShips(2, "ARQUITENS_EMPIRE", "IMOBILIZER_EMPIRE", "DREADNOUGHTHEAVYCRUISER_EMPIRE", "ACCLIMATOR_EMPIRE", "IMPERIAL_II_EMPIRE", "GLADIATOR_EMPIRE", "VINDICATOR_EMPIRE", "PURSUIT_EMPIRE", "VENATOR_EMPIRE")
    .addBuildableShips(3, "IMPERIAL_CARGO_SHIP_EMPIRE", "VICTORYSTARDESTROYER_EMPIRE", "CRIMSONCOMMAND_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "AGGRESSORSTARDESTROYER_EMPIRE", "ALLEGIANCE_EMPIRE", "TORPEDO_SPHERE_EMPIRE")
    .addBuildableShips(4, "CONSOLIDATORASSAULTSHIP_EMPIRE", "COMPELLOR_EMPIRE", "ARCHAMMER_EMPIRE", "EXECUTORSUPERSTARDESTROYER_EMPIRE", "BELLATORSUPERSTARDESTROYER_EMPIRE", "ASSERTORSTARDREADNOUGHT_EMPIRE", "LEGATORSTARDREADNOUGHT_EMPIRE", "VENGEANCE_EMPIRE")
    .addStationOptions("GOLAN_I_EMPIRE", "GOLAN_II_EMPIRE", "GOLAN_III_EMPIRE")
    .addShipyardOptions("SHIPYARD_LVL_1_EMPIRE", "SHIPYARD_LVL_2_EMPIRE", "SHIPYARD_LVL_3_EMPIRE", "SHIPYARD_LVL_4_EMPIRE");

export const maldrood = new FactionConfig("Greater Maldrood", "#ff4d4d", "EMPIRE")
    .addBuildableShips(1, "CUSTOMS_EMPIRE", "RAIDER_EMPIRE", "RAIDER_II_EMPIRE", "VIGILCORVETTE_EMPIRE", "CARRACK_EMPIRE", "LANCERFRIGATE_EMPIRE", "TARTAN_PATROL_CRUISER_EMPIRE")
    .addBuildableShips(2, "PURSUIT_EMPIRE", "STARGALLEON_EMPIRE", "SURVEYOR_EMPIRE", "VINDICATOR_EMPIRE", "ACCLIMATOR_EMPIRE", "IMPERIAL_II_EMPIRE")
    .addBuildableShips(3, "VICTORYSTARDESTROYER_EMPIRE", "CRIMSONCOMMAND_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "TECTOR_STAR_DESTROYER_EMPIRE")
    .addBuildableShips(4, "COMMUNICATIONS_BATTLECRUISER_EMPIRE", "PRAETOR_II_EMPIRE", "LEGATORSTARDREADNOUGHT_EMPIRE")
    .addStationOptions("GOLAN_I_EMPIRE", "GOLAN_II_EMPIRE", "GOLAN_III_EMPIRE")
    .addShipyardOptions("SHIPYARD_LVL_1_EMPIRE", "SHIPYARD_LVL_2_EMPIRE", "SHIPYARD_LVL_3_EMPIRE", "SHIPYARD_LVL_4_EMPIRE");

export const eriaduAuthority = new FactionConfig("Eriadu Authority", "#5c5c8a", "EMPIRE")
    .addBuildableShips(1, "IPV1_EMPIRE", "RAIDER_EMPIRE", "VICTORYFRIGATE_EMPIRE", "STRIKECRUISER_EMPIRE", "CARRACK_EMPIRE")
    .addBuildableShips(2, "STARGALLEON_EMPIRE", "IMPERIAL_II_EMPIRE", "GLADIATOR_EMPIRE")
    .addBuildableShips(3, "VICTORYSTARDESTROYER_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "ALLEGIANCE_EMPIRE", "TORPEDO_SPHERE_EMPIRE")
    .addBuildableShips(4, "TAGGE_BATTLECRUISER_EMPIRE", "PRAETOR_II_EMPIRE")
    .addStationOptions("GOLAN_I_EMPIRE", "GOLAN_II_EMPIRE", "GOLAN_III_EMPIRE")
    .addShipyardOptions("SHIPYARD_LVL_1_EMPIRE", "SHIPYARD_LVL_2_EMPIRE", "SHIPYARD_LVL_3_EMPIRE", "SHIPYARD_LVL_4_EMPIRE");

export const pentastarAlignment = new FactionConfig("Pentastar Alignment", "#5555C8", "EMPIRE")
    .addBuildableShips(1, "RAIDER_EMPIRE", "BUCCANEER_EMPIRE", "CR92A_EMPIRE", "TRENCHANT_CRUISER_EMPIRE", "TONFALKCARRIER_EMPIRE", "VICTORYFRIGATE_EMPIRE", "TARTAN_PATROL_CRUISER_EMPIRE")
    .addBuildableShips(2, "ACCLIMATOR_EMPIRE", "VINDICATOR_EMPIRE", "DREADNOUGHTHEAVYCRUISER_EMPIRE", "NEUTRON_STAR_EMPIRE")
    .addBuildableShips(3, "VENATOR_EMPIRE", "PROCURSATOR_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "TECTOR_STAR_DESTROYER_EMPIRE")
    .addBuildableShips(4, "PRAETOR_CARRIER_EMPIRE", "SORONNAN_EMPIRE", "SECUTOR_EMPIRE")
    .addStationOptions("GOLAN_I_EMPIRE", "GOLAN_II_EMPIRE", "GOLAN_III_EMPIRE")
    .addShipyardOptions("SHIPYARD_LVL_1_EMPIRE", "SHIPYARD_LVL_2_EMPIRE", "SHIPYARD_LVL_3_EMPIRE", "SHIPYARD_LVL_4_EMPIRE");

export const zsinj = new FactionConfig("Zsinj's Empire", "#b3b300", "EMPIRE")
    .addBuildableShips(1, "RAIDER_EMPIRE", "RAIDER_II_EMPIRE", "VIGILCORVETTE_EMPIRE", "CR92A_EMPIRE", "BUCCANEER_EMPIRE", "SURVEYOR_EMPIRE", "LANCERFRIGATE_EMPIRE", "CARRACK_EMPIRE")
    .addBuildableShips(2, "NEBULONB_EMPIRE", "STARGALLEON_EMPIRE", "QUASAR_EMPIRE", "VENGEANCE_FRIGATE_EMPIRE", "DRAGON_HEAVY_CRUISER_EMPIRE", "NEUTRON_STAR_EMPIRE")
    .addBuildableShips(3, "VICTORYSTARDESTROYER_EMPIRE", "IMPERIALSTARDESTROYER_EMPIRE", "TECTOR_STAR_DESTROYER_EMPIRE", "ALLEGIANCE_EMPIRE")
    .addBuildableShips(4, "COMMUNICATIONS_BATTLECRUISER_EMPIRE", "SORONNAN_EMPIRE", "COMPELLOR_EMPIRE")
    .addStationOptions("GOLAN_I_EMPIRE", "GOLAN_II_EMPIRE", "GOLAN_III_EMPIRE")
    .addShipyardOptions("SHIPYARD_LVL_1_EMPIRE", "SHIPYARD_LVL_2_EMPIRE", "SHIPYARD_LVL_3_EMPIRE", "SHIPYARD_LVL_4_EMPIRE");

export const eoth = new FactionConfig("Empire of the Hand", "#00b8e6", "EOTH")
    .addBuildableShips(1, "ASDONI_EOTH", "KUURO_EOTH", "SYZYGOS_EOTH")
    .addBuildableShips(2, "BAOMU_EOTH", "FRUORO_EOTH", "KYNIGOS_EOTH", "PROLIPSI_EOTH")
    .addBuildableShips(3, "ORMOS_EOTH", "CHAF_EOTH", "EFODIO_EOTH")
    .addBuildableShips(4, "ASCENDANCY_EOTH", "SYNDIC_EOTH", "INTEGO_EOTH")
    .addStationOptions("GOLAN_I_EOTH", "GOLAN_II_EOTH", "GOLAN_III_EOTH")
    .addShipyardOptions("SHIPYARD_LVL_1_EOTH", "SHIPYARD_LVL_2_EOTH", "SHIPYARD_LVL_3_EOTH", "SHIPYARD_LVL_4_EOTH");