import ships from "../../server/lib/ships.js";
import { FactionConfig } from "../baseFactions.js"

export const independentPostEndor = new FactionConfig("Independent Forces", "#FFFFFF", "")
    .addBuildableShips(1, "LUPUSMISSILEFRIGATE_CIS", "DIAMOND_CIS", "HARDCELL_CIS", "C9979_CIS", "MUNIFICENT_CIS")
    .addBuildableShips(1, "RECUSANT_CIS", "MUNIFICENT_HEAVY_CIS", "PROVIDENCEDESTROYER_CIS", "LUCREHULKAUXILIARYWARSHIP_CIS")
    .addBuildableShips(1, "VENATOR_EMPIRE", "CONSOLAR_REPUBLIC", "CR90_REPUBLIC", "CR92A_EMPIRE", "BUCCANEER_ZANN", "PELTA_REPUBLIC")
    .addBuildableShips(1, "ARQUITENS_REPUBLIC", "ACCLIMATOR_REPUBLIC", "ACTIONVITRANSPORT_HUTT", "ACTIONVITRANSPORT_ZANN", "SUPER_TRANSPORT_XI_EMPIRE")
    .addBuildableShips(1, "CRUSADERCORVETTE_ZANN", "DP20_ZANN", "DREADNOUGHTHEAVYCRUISER_REPUBLIC", "DREADNOUGHTHEAVYCRUISER_REBEL", "DREADNOUGHTHEAVYCRUISER_EMPIRE");
